routes/web.php
<?php

Auth::routes(['register' => false]);

// Change Password Routes...
Route::get('change_password', 'Auth\ChangePasswordController@showChangePasswordForm')->name('auth.change_password');
Route::patch('change_password', 'Auth\ChangePasswordController@changePassword')->name('auth.change_password');
Route::post('review/store', 'Admin\ReviewController@store')->name('review.store');

Route::group(['middleware' => ['auth'], 'prefix' => 'admin', 'as' => 'admin.'], function () {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('permissions', 'Admin\PermissionsController');
    Route::post('permissions_mass_destroy', 'Admin\PermissionsController@massDestroy')->name('permissions.mass_destroy');
    Route::resource('roles', 'Admin\RolesController');
    Route::post('roles_mass_destroy', 'Admin\RolesController@massDestroy')->name('roles.mass_destroy');
    Route::resource('users', 'Admin\UsersController');
    Route::post('users_mass_destroy', 'Admin\UsersController@massDestroy')->name('users.mass_destroy');
    Route::resource('categories', 'Admin\CategoriesController');
    Route::post('categories_mass_destroy', 'Admin\CategoriesController@massDestroy')->name('categories.mass_destroy');
    Route::resource('banners', 'Admin\BannersController');
    Route::post('banners_mass_destroy', 'Admin\BannersController@massDestroy')->name('banners.mass_destroy');
    Route::resource('pages', 'Admin\PagesController');
    Route::post('pages_mass_destroy', 'Admin\PagesController@massDestroy')->name('pages.mass_destroy');
    Route::resource('products', 'Admin\ProductsController');
    Route::post('products_mass_destroy', 'Admin\ProductsController@massDestroy')->name('products.mass_destroy');
    Route::get('products-mass-update', 'Admin\ProductsController@massUpdate')->name('products.mass_update');
    Route::resource('enquiries', 'Admin\EnquiriesController');
    Route::post('enquiries_mass_destroy', 'Admin\EnquiriesController@massDestroy')->name('enquiries.mass_destroy');
    Route::resource('review', 'Admin\ReviewController');
    Route::post('review/approve', 'Admin\ReviewController@review_approve')->name('review.approve');
    Route::post('review_mass_destroy', 'Admin\ReviewController@massDestroy')->name('review.mass_destroy');
    Route::resource('product-enquiries', 'Admin\ProductEnquiriesController');
    Route::post('product_enquiries_mass_destroy', 'Admin\ProductEnquiriesController@massDestroy')->name('product_enquiries.mass_destroy');
    Route::get('/products/delete-image/{id}', 'Admin\ProductsController@deleteImage')->name('delete_image');
    Route::get('/products/delete-video/{id}', 'Admin\ProductsController@deleteVideo')->name('delete_video');
});

Route::get('/', 'Site\HomeController@index')->name('home');
Route::get('/about-us', 'Site\AboutController@index')->name('about');
Route::get('/contact-us', 'Site\ContactController@index')->name('contact-us');
Route::get('/return-policy', 'Site\PageController@returnPolicy')->name('return-policy');
Route::get('/faq', 'Site\PageController@faq')->name('faq');
Route::get('/{slug}', 'Site\CategoryController@index')->name('category');
Route::post('/contact-us', 'Site\ContactController@sendMessage')->name('contact-submit');

resources/views/home.blade.php
@extends('layouts.admin')

@section('content')
<div class="content">
    <div class="row">
        <div class="col-6 col-lg-3">
            <div class="card">
                <div class="card-body p-6 d-flex align-items-center">
                    <i class="fa fa-tasks bg-primary p-3 font-2xl mr-3"></i>
                <div>
                <div class="text-value-sm text-primary">{{\App\Models\Category::active()->count()}}</div>
                    <div class="text-muted text-uppercase font-weight-bold small">Categories</div>
                    </div>
                </div>
                <div class="card-footer px-3 py-6">
                    <a class="btn-block text-muted d-flex justify-content-between align-items-center" href="{{ route('admin.categories.index') }}">
                        <span class="small font-weight-bold">View All</span>
                        <i class="fa fa-angle-right"></i>
                    </a>
                </div>
            </div>
        </div>
        <div class="col-6 col-lg-3">
            <div class="card">
                <div class="card-body p-6 d-flex align-items-center">
                    <i class="fa fa-box-open bg-success p-3 font-2xl mr-3"></i>
                <div>
                <div class="text-value-sm text-success">{{\App\Models\Product::active()->count()}}</div>
                    <div class="text-muted text-uppercase font-weight-bold small">Products</div>
                    </div>
                </div>
                <div class="card-footer px-3 py-6">
                    <a class="btn-block text-muted d-flex justify-content-between align-items-center" href="{{ route('admin.products.index') }}">
                        <span class="small font-weight-bold">View All</span>
                        <i class="fa fa-angle-right"></i>
                    </a>
                </div>
            </div>
        </div>
        <div class="col-6 col-lg-3">
            <div class="card">
                <div class="card-body p-6 d-flex align-items-center">
                    <i class="fa fa-images bg-warning p-3 font-2xl mr-3"></i>
                <div>
                <div class="text-value-sm text-warning">{{\App\Models\Banner::active()->count()}}</div>
                    <div class="text-muted text-uppercase font-weight-bold small">Banners</div>
                    </div>
                </div>
                <div class="card-footer px-3 py-6">
                    <a class="btn-block text-muted d-flex justify-content-between align-items-center" href="{{ route('admin.banners.index') }}">
                        <span class="small font-weight-bold">View All</span>
                        <i class="fa fa-angle-right"></i>
                    </a>
                </div>
            </div>
        </div>
        <div class="col-6 col-lg-3">
            <div class="card">
                <div class="card-body p-6 d-flex align-items-center">
                    <i class="fa fa-book-open bg-danger p-3 font-2xl mr-3"></i>
                <div>
                <div class="text-value-sm text-danger">{{\App\Models\Page::count()}}</div>
                    <div class="text-muted text-uppercase font-weight-bold small">Pages</div>
                    </div>
                </div>
                <div class="card-footer px-3 py-6">
                    <a class="btn-block text-muted d-flex justify-content-between align-items-center" href="{{ route('admin.pages.index') }}">
                        <span class="small font-weight-bold">View All</span>
                        <i class="fa fa-angle-right"></i>
                    </a>
                </div>
            </div>
        </div>
    </div>
    <div class="card-group mb-4">
        <div class="card">
            <div class="card-body">
                <div class="h1 text-muted text-right mb-4">
                    <i class="text-success fas fa-envelope"></i>
                </div>
                <div class="text-value text-success">{{\App\Models\Enquiry::count()}}</div>
                <small class="text-muted clr-def text-uppercase font-weight-bold">Enquiries</small>
            </div>
        </div>
        <div class="card">
            <div class="card-body">
                <div class="h1 text-muted text-right mb-4">
                    <i class="text-primary fas fa-envelope-square"></i>
                </div>
                <div class="text-value text-primary">{{\App\Models\ProductEnquiry::count()}}</div>
                <small class="text-muted clr-def text-uppercase font-weight-bold">Product Enquiries</small>
            </div>
        </div>
    </div>
</div>
@endsection
@section('scripts')
@parent

@endsection